version: '3.8'

services:
  db:
    image: postgres:15
    container_name: reservoir_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: reservoir_simulation
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: reservoir_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:secretpassword@db:5432/reservoir_simulation
volumes:
  postgres_data: